name: flet_video_compressor
description: Flet FletVideoCompressor control
repository: https://github.com/MyGithubAccount/flet-video-compressor/src/flutter/flet_video_compressor
version: 0.1.0
homepage: https://github.com/MyGithubAccount/flet-video-compressor

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 0.26.0
  flutter:
    sdk: flutter
  light_compressor: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
